// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ravuno.DataStorage;

#nullable disable

namespace Ravuno.DataStorage.Migrations
{
    [DbContext(typeof(DataStorageContext))]
    [Migration("20260202122611_UniqueSourceSourceIdOnItems")]
    partial class UniqueSourceSourceIdOnItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Ravuno.DataStorage.Models.FetchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ExecutionDuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutionStartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDetailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsRetrieved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewItems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdatedItems")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FetchHistories");
                });

            modelBuilder.Entity("Ravuno.DataStorage.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnrollmentDeadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventEndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventStartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organizer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Source", "SourceId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Ravuno.DataStorage.Models.SendUpdateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailReceiverAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("NewItemsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueryTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdatedItemsCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SendUpdateHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
